package: pill
user: malev

platform:
  - linux-32
  - linux-64
  - osx-64

engine:
  - python=2.7
  - python=3.4

script:
  - conda install pill -c malev -y
  - pill
  - pill init
  - source pill in
  - source pill out

build_targets: conda
