package:
  name: pill
  version: "0.3.0"

build:
  always_include_files:
    - bin/pill              [unix]
    - Scripts/pill.bat      [win]

source:
  path: ../

about:
  home: https://github.com/malev/pill
